#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -q workq
#PBS -r n
#PBS -l walltime=48:00:00
#PBS -N RVmodelCV_1_0_198_1_20
# EVERYTHING ABOVE THIS COMMENT IS NECESSARY, SHOULD ONLY CHANGE nodes,ppn,walltime and my_job_name VALUES
cd $PBS_O_WORKDIR
python CVmodelcomparison_qsubjob.py 1 0 198 1 20
